// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPluginsNbGatewaysGatewayListParams creates a new PluginsNbGatewaysGatewayListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPluginsNbGatewaysGatewayListParams() *PluginsNbGatewaysGatewayListParams {
	return &PluginsNbGatewaysGatewayListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPluginsNbGatewaysGatewayListParamsWithTimeout creates a new PluginsNbGatewaysGatewayListParams object
// with the ability to set a timeout on a request.
func NewPluginsNbGatewaysGatewayListParamsWithTimeout(timeout time.Duration) *PluginsNbGatewaysGatewayListParams {
	return &PluginsNbGatewaysGatewayListParams{
		timeout: timeout,
	}
}

// NewPluginsNbGatewaysGatewayListParamsWithContext creates a new PluginsNbGatewaysGatewayListParams object
// with the ability to set a context for a request.
func NewPluginsNbGatewaysGatewayListParamsWithContext(ctx context.Context) *PluginsNbGatewaysGatewayListParams {
	return &PluginsNbGatewaysGatewayListParams{
		Context: ctx,
	}
}

// NewPluginsNbGatewaysGatewayListParamsWithHTTPClient creates a new PluginsNbGatewaysGatewayListParams object
// with the ability to set a custom HTTPClient for a request.
func NewPluginsNbGatewaysGatewayListParamsWithHTTPClient(client *http.Client) *PluginsNbGatewaysGatewayListParams {
	return &PluginsNbGatewaysGatewayListParams{
		HTTPClient: client,
	}
}

/*
PluginsNbGatewaysGatewayListParams contains all the parameters to send to the API endpoint

	for the plugins nb gateways gateway list operation.

	Typically these are written to a http.Request.
*/
type PluginsNbGatewaysGatewayListParams struct {

	// Created.
	Created *string

	// CreatedGt.
	CreatedGt *string

	// CreatedGte.
	CreatedGte *string

	// CreatedLt.
	CreatedLt *string

	// CreatedLte.
	CreatedLte *string

	// Createdn.
	Createdn *string

	// GatewayIP.
	GatewayIP *string

	// GatewayIPn.
	GatewayIPn *string

	// ID.
	ID *string

	// IDGt.
	IDGt *string

	// IDGte.
	IDGte *string

	// IDLt.
	IDLt *string

	// IDLte.
	IDLte *string

	// IDn.
	IDn *string

	// LastUpdated.
	LastUpdated *string

	// LastUpdatedGt.
	LastUpdatedGt *string

	// LastUpdatedGte.
	LastUpdatedGte *string

	// LastUpdatedLt.
	LastUpdatedLt *string

	// LastUpdatedLte.
	LastUpdatedLte *string

	// LastUpdatedn.
	LastUpdatedn *string

	/* Limit.

	   Number of results to return per page.
	*/
	Limit *int64

	/* Offset.

	   The initial index from which to return the results.
	*/
	Offset *int64

	/* Ordering.

	   Which field to use when ordering the results.
	*/
	Ordering *string

	// Prefix.
	Prefix *string

	// Prefixn.
	Prefixn *string

	// Q.
	Q *string

	// Tag.
	Tag *string

	// Tagn.
	Tagn *string

	// Vrf.
	Vrf *string

	// Vrfn.
	Vrfn *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the plugins nb gateways gateway list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNbGatewaysGatewayListParams) WithDefaults() *PluginsNbGatewaysGatewayListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the plugins nb gateways gateway list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNbGatewaysGatewayListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithTimeout(timeout time.Duration) *PluginsNbGatewaysGatewayListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithContext(ctx context.Context) *PluginsNbGatewaysGatewayListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithHTTPClient(client *http.Client) *PluginsNbGatewaysGatewayListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreated adds the created to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithCreated(created *string) *PluginsNbGatewaysGatewayListParams {
	o.SetCreated(created)
	return o
}

// SetCreated adds the created to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetCreated(created *string) {
	o.Created = created
}

// WithCreatedGt adds the createdGt to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithCreatedGt(createdGt *string) *PluginsNbGatewaysGatewayListParams {
	o.SetCreatedGt(createdGt)
	return o
}

// SetCreatedGt adds the createdGt to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetCreatedGt(createdGt *string) {
	o.CreatedGt = createdGt
}

// WithCreatedGte adds the createdGte to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithCreatedGte(createdGte *string) *PluginsNbGatewaysGatewayListParams {
	o.SetCreatedGte(createdGte)
	return o
}

// SetCreatedGte adds the createdGte to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetCreatedGte(createdGte *string) {
	o.CreatedGte = createdGte
}

// WithCreatedLt adds the createdLt to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithCreatedLt(createdLt *string) *PluginsNbGatewaysGatewayListParams {
	o.SetCreatedLt(createdLt)
	return o
}

// SetCreatedLt adds the createdLt to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetCreatedLt(createdLt *string) {
	o.CreatedLt = createdLt
}

// WithCreatedLte adds the createdLte to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithCreatedLte(createdLte *string) *PluginsNbGatewaysGatewayListParams {
	o.SetCreatedLte(createdLte)
	return o
}

// SetCreatedLte adds the createdLte to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetCreatedLte(createdLte *string) {
	o.CreatedLte = createdLte
}

// WithCreatedn adds the createdn to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithCreatedn(createdn *string) *PluginsNbGatewaysGatewayListParams {
	o.SetCreatedn(createdn)
	return o
}

// SetCreatedn adds the createdN to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetCreatedn(createdn *string) {
	o.Createdn = createdn
}

// WithGatewayIP adds the gatewayIP to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithGatewayIP(gatewayIP *string) *PluginsNbGatewaysGatewayListParams {
	o.SetGatewayIP(gatewayIP)
	return o
}

// SetGatewayIP adds the gatewayIp to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetGatewayIP(gatewayIP *string) {
	o.GatewayIP = gatewayIP
}

// WithGatewayIPn adds the gatewayIPn to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithGatewayIPn(gatewayIPn *string) *PluginsNbGatewaysGatewayListParams {
	o.SetGatewayIPn(gatewayIPn)
	return o
}

// SetGatewayIPn adds the gatewayIpN to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetGatewayIPn(gatewayIPn *string) {
	o.GatewayIPn = gatewayIPn
}

// WithID adds the id to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithID(id *string) *PluginsNbGatewaysGatewayListParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetID(id *string) {
	o.ID = id
}

// WithIDGt adds the iDGt to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithIDGt(iDGt *string) *PluginsNbGatewaysGatewayListParams {
	o.SetIDGt(iDGt)
	return o
}

// SetIDGt adds the idGt to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetIDGt(iDGt *string) {
	o.IDGt = iDGt
}

// WithIDGte adds the iDGte to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithIDGte(iDGte *string) *PluginsNbGatewaysGatewayListParams {
	o.SetIDGte(iDGte)
	return o
}

// SetIDGte adds the idGte to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetIDGte(iDGte *string) {
	o.IDGte = iDGte
}

// WithIDLt adds the iDLt to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithIDLt(iDLt *string) *PluginsNbGatewaysGatewayListParams {
	o.SetIDLt(iDLt)
	return o
}

// SetIDLt adds the idLt to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetIDLt(iDLt *string) {
	o.IDLt = iDLt
}

// WithIDLte adds the iDLte to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithIDLte(iDLte *string) *PluginsNbGatewaysGatewayListParams {
	o.SetIDLte(iDLte)
	return o
}

// SetIDLte adds the idLte to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetIDLte(iDLte *string) {
	o.IDLte = iDLte
}

// WithIDn adds the iDn to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithIDn(iDn *string) *PluginsNbGatewaysGatewayListParams {
	o.SetIDn(iDn)
	return o
}

// SetIDn adds the idN to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetIDn(iDn *string) {
	o.IDn = iDn
}

// WithLastUpdated adds the lastUpdated to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithLastUpdated(lastUpdated *string) *PluginsNbGatewaysGatewayListParams {
	o.SetLastUpdated(lastUpdated)
	return o
}

// SetLastUpdated adds the lastUpdated to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetLastUpdated(lastUpdated *string) {
	o.LastUpdated = lastUpdated
}

// WithLastUpdatedGt adds the lastUpdatedGt to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithLastUpdatedGt(lastUpdatedGt *string) *PluginsNbGatewaysGatewayListParams {
	o.SetLastUpdatedGt(lastUpdatedGt)
	return o
}

// SetLastUpdatedGt adds the lastUpdatedGt to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetLastUpdatedGt(lastUpdatedGt *string) {
	o.LastUpdatedGt = lastUpdatedGt
}

// WithLastUpdatedGte adds the lastUpdatedGte to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithLastUpdatedGte(lastUpdatedGte *string) *PluginsNbGatewaysGatewayListParams {
	o.SetLastUpdatedGte(lastUpdatedGte)
	return o
}

// SetLastUpdatedGte adds the lastUpdatedGte to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetLastUpdatedGte(lastUpdatedGte *string) {
	o.LastUpdatedGte = lastUpdatedGte
}

// WithLastUpdatedLt adds the lastUpdatedLt to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithLastUpdatedLt(lastUpdatedLt *string) *PluginsNbGatewaysGatewayListParams {
	o.SetLastUpdatedLt(lastUpdatedLt)
	return o
}

// SetLastUpdatedLt adds the lastUpdatedLt to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetLastUpdatedLt(lastUpdatedLt *string) {
	o.LastUpdatedLt = lastUpdatedLt
}

// WithLastUpdatedLte adds the lastUpdatedLte to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithLastUpdatedLte(lastUpdatedLte *string) *PluginsNbGatewaysGatewayListParams {
	o.SetLastUpdatedLte(lastUpdatedLte)
	return o
}

// SetLastUpdatedLte adds the lastUpdatedLte to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetLastUpdatedLte(lastUpdatedLte *string) {
	o.LastUpdatedLte = lastUpdatedLte
}

// WithLastUpdatedn adds the lastUpdatedn to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithLastUpdatedn(lastUpdatedn *string) *PluginsNbGatewaysGatewayListParams {
	o.SetLastUpdatedn(lastUpdatedn)
	return o
}

// SetLastUpdatedn adds the lastUpdatedN to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetLastUpdatedn(lastUpdatedn *string) {
	o.LastUpdatedn = lastUpdatedn
}

// WithLimit adds the limit to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithLimit(limit *int64) *PluginsNbGatewaysGatewayListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithOffset(offset *int64) *PluginsNbGatewaysGatewayListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithOrdering adds the ordering to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithOrdering(ordering *string) *PluginsNbGatewaysGatewayListParams {
	o.SetOrdering(ordering)
	return o
}

// SetOrdering adds the ordering to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetOrdering(ordering *string) {
	o.Ordering = ordering
}

// WithPrefix adds the prefix to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithPrefix(prefix *string) *PluginsNbGatewaysGatewayListParams {
	o.SetPrefix(prefix)
	return o
}

// SetPrefix adds the prefix to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetPrefix(prefix *string) {
	o.Prefix = prefix
}

// WithPrefixn adds the prefixn to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithPrefixn(prefixn *string) *PluginsNbGatewaysGatewayListParams {
	o.SetPrefixn(prefixn)
	return o
}

// SetPrefixn adds the prefixN to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetPrefixn(prefixn *string) {
	o.Prefixn = prefixn
}

// WithQ adds the q to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithQ(q *string) *PluginsNbGatewaysGatewayListParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetQ(q *string) {
	o.Q = q
}

// WithTag adds the tag to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithTag(tag *string) *PluginsNbGatewaysGatewayListParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetTag(tag *string) {
	o.Tag = tag
}

// WithTagn adds the tagn to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithTagn(tagn *string) *PluginsNbGatewaysGatewayListParams {
	o.SetTagn(tagn)
	return o
}

// SetTagn adds the tagN to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetTagn(tagn *string) {
	o.Tagn = tagn
}

// WithVrf adds the vrf to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithVrf(vrf *string) *PluginsNbGatewaysGatewayListParams {
	o.SetVrf(vrf)
	return o
}

// SetVrf adds the vrf to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetVrf(vrf *string) {
	o.Vrf = vrf
}

// WithVrfn adds the vrfn to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) WithVrfn(vrfn *string) *PluginsNbGatewaysGatewayListParams {
	o.SetVrfn(vrfn)
	return o
}

// SetVrfn adds the vrfN to the plugins nb gateways gateway list params
func (o *PluginsNbGatewaysGatewayListParams) SetVrfn(vrfn *string) {
	o.Vrfn = vrfn
}

// WriteToRequest writes these params to a swagger request
func (o *PluginsNbGatewaysGatewayListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Created != nil {

		// query param created
		var qrCreated string

		if o.Created != nil {
			qrCreated = *o.Created
		}
		qCreated := qrCreated
		if qCreated != "" {

			if err := r.SetQueryParam("created", qCreated); err != nil {
				return err
			}
		}
	}

	if o.CreatedGt != nil {

		// query param created__gt
		var qrCreatedGt string

		if o.CreatedGt != nil {
			qrCreatedGt = *o.CreatedGt
		}
		qCreatedGt := qrCreatedGt
		if qCreatedGt != "" {

			if err := r.SetQueryParam("created__gt", qCreatedGt); err != nil {
				return err
			}
		}
	}

	if o.CreatedGte != nil {

		// query param created__gte
		var qrCreatedGte string

		if o.CreatedGte != nil {
			qrCreatedGte = *o.CreatedGte
		}
		qCreatedGte := qrCreatedGte
		if qCreatedGte != "" {

			if err := r.SetQueryParam("created__gte", qCreatedGte); err != nil {
				return err
			}
		}
	}

	if o.CreatedLt != nil {

		// query param created__lt
		var qrCreatedLt string

		if o.CreatedLt != nil {
			qrCreatedLt = *o.CreatedLt
		}
		qCreatedLt := qrCreatedLt
		if qCreatedLt != "" {

			if err := r.SetQueryParam("created__lt", qCreatedLt); err != nil {
				return err
			}
		}
	}

	if o.CreatedLte != nil {

		// query param created__lte
		var qrCreatedLte string

		if o.CreatedLte != nil {
			qrCreatedLte = *o.CreatedLte
		}
		qCreatedLte := qrCreatedLte
		if qCreatedLte != "" {

			if err := r.SetQueryParam("created__lte", qCreatedLte); err != nil {
				return err
			}
		}
	}

	if o.Createdn != nil {

		// query param created__n
		var qrCreatedn string

		if o.Createdn != nil {
			qrCreatedn = *o.Createdn
		}
		qCreatedn := qrCreatedn
		if qCreatedn != "" {

			if err := r.SetQueryParam("created__n", qCreatedn); err != nil {
				return err
			}
		}
	}

	if o.GatewayIP != nil {

		// query param gateway_ip
		var qrGatewayIP string

		if o.GatewayIP != nil {
			qrGatewayIP = *o.GatewayIP
		}
		qGatewayIP := qrGatewayIP
		if qGatewayIP != "" {

			if err := r.SetQueryParam("gateway_ip", qGatewayIP); err != nil {
				return err
			}
		}
	}

	if o.GatewayIPn != nil {

		// query param gateway_ip__n
		var qrGatewayIPn string

		if o.GatewayIPn != nil {
			qrGatewayIPn = *o.GatewayIPn
		}
		qGatewayIPn := qrGatewayIPn
		if qGatewayIPn != "" {

			if err := r.SetQueryParam("gateway_ip__n", qGatewayIPn); err != nil {
				return err
			}
		}
	}

	if o.ID != nil {

		// query param id
		var qrID string

		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {

			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}
	}

	if o.IDGt != nil {

		// query param id__gt
		var qrIDGt string

		if o.IDGt != nil {
			qrIDGt = *o.IDGt
		}
		qIDGt := qrIDGt
		if qIDGt != "" {

			if err := r.SetQueryParam("id__gt", qIDGt); err != nil {
				return err
			}
		}
	}

	if o.IDGte != nil {

		// query param id__gte
		var qrIDGte string

		if o.IDGte != nil {
			qrIDGte = *o.IDGte
		}
		qIDGte := qrIDGte
		if qIDGte != "" {

			if err := r.SetQueryParam("id__gte", qIDGte); err != nil {
				return err
			}
		}
	}

	if o.IDLt != nil {

		// query param id__lt
		var qrIDLt string

		if o.IDLt != nil {
			qrIDLt = *o.IDLt
		}
		qIDLt := qrIDLt
		if qIDLt != "" {

			if err := r.SetQueryParam("id__lt", qIDLt); err != nil {
				return err
			}
		}
	}

	if o.IDLte != nil {

		// query param id__lte
		var qrIDLte string

		if o.IDLte != nil {
			qrIDLte = *o.IDLte
		}
		qIDLte := qrIDLte
		if qIDLte != "" {

			if err := r.SetQueryParam("id__lte", qIDLte); err != nil {
				return err
			}
		}
	}

	if o.IDn != nil {

		// query param id__n
		var qrIDn string

		if o.IDn != nil {
			qrIDn = *o.IDn
		}
		qIDn := qrIDn
		if qIDn != "" {

			if err := r.SetQueryParam("id__n", qIDn); err != nil {
				return err
			}
		}
	}

	if o.LastUpdated != nil {

		// query param last_updated
		var qrLastUpdated string

		if o.LastUpdated != nil {
			qrLastUpdated = *o.LastUpdated
		}
		qLastUpdated := qrLastUpdated
		if qLastUpdated != "" {

			if err := r.SetQueryParam("last_updated", qLastUpdated); err != nil {
				return err
			}
		}
	}

	if o.LastUpdatedGt != nil {

		// query param last_updated__gt
		var qrLastUpdatedGt string

		if o.LastUpdatedGt != nil {
			qrLastUpdatedGt = *o.LastUpdatedGt
		}
		qLastUpdatedGt := qrLastUpdatedGt
		if qLastUpdatedGt != "" {

			if err := r.SetQueryParam("last_updated__gt", qLastUpdatedGt); err != nil {
				return err
			}
		}
	}

	if o.LastUpdatedGte != nil {

		// query param last_updated__gte
		var qrLastUpdatedGte string

		if o.LastUpdatedGte != nil {
			qrLastUpdatedGte = *o.LastUpdatedGte
		}
		qLastUpdatedGte := qrLastUpdatedGte
		if qLastUpdatedGte != "" {

			if err := r.SetQueryParam("last_updated__gte", qLastUpdatedGte); err != nil {
				return err
			}
		}
	}

	if o.LastUpdatedLt != nil {

		// query param last_updated__lt
		var qrLastUpdatedLt string

		if o.LastUpdatedLt != nil {
			qrLastUpdatedLt = *o.LastUpdatedLt
		}
		qLastUpdatedLt := qrLastUpdatedLt
		if qLastUpdatedLt != "" {

			if err := r.SetQueryParam("last_updated__lt", qLastUpdatedLt); err != nil {
				return err
			}
		}
	}

	if o.LastUpdatedLte != nil {

		// query param last_updated__lte
		var qrLastUpdatedLte string

		if o.LastUpdatedLte != nil {
			qrLastUpdatedLte = *o.LastUpdatedLte
		}
		qLastUpdatedLte := qrLastUpdatedLte
		if qLastUpdatedLte != "" {

			if err := r.SetQueryParam("last_updated__lte", qLastUpdatedLte); err != nil {
				return err
			}
		}
	}

	if o.LastUpdatedn != nil {

		// query param last_updated__n
		var qrLastUpdatedn string

		if o.LastUpdatedn != nil {
			qrLastUpdatedn = *o.LastUpdatedn
		}
		qLastUpdatedn := qrLastUpdatedn
		if qLastUpdatedn != "" {

			if err := r.SetQueryParam("last_updated__n", qLastUpdatedn); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Ordering != nil {

		// query param ordering
		var qrOrdering string

		if o.Ordering != nil {
			qrOrdering = *o.Ordering
		}
		qOrdering := qrOrdering
		if qOrdering != "" {

			if err := r.SetQueryParam("ordering", qOrdering); err != nil {
				return err
			}
		}
	}

	if o.Prefix != nil {

		// query param prefix
		var qrPrefix string

		if o.Prefix != nil {
			qrPrefix = *o.Prefix
		}
		qPrefix := qrPrefix
		if qPrefix != "" {

			if err := r.SetQueryParam("prefix", qPrefix); err != nil {
				return err
			}
		}
	}

	if o.Prefixn != nil {

		// query param prefix__n
		var qrPrefixn string

		if o.Prefixn != nil {
			qrPrefixn = *o.Prefixn
		}
		qPrefixn := qrPrefixn
		if qPrefixn != "" {

			if err := r.SetQueryParam("prefix__n", qPrefixn); err != nil {
				return err
			}
		}
	}

	if o.Q != nil {

		// query param q
		var qrQ string

		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {

			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}
	}

	if o.Tag != nil {

		// query param tag
		var qrTag string

		if o.Tag != nil {
			qrTag = *o.Tag
		}
		qTag := qrTag
		if qTag != "" {

			if err := r.SetQueryParam("tag", qTag); err != nil {
				return err
			}
		}
	}

	if o.Tagn != nil {

		// query param tag__n
		var qrTagn string

		if o.Tagn != nil {
			qrTagn = *o.Tagn
		}
		qTagn := qrTagn
		if qTagn != "" {

			if err := r.SetQueryParam("tag__n", qTagn); err != nil {
				return err
			}
		}
	}

	if o.Vrf != nil {

		// query param vrf
		var qrVrf string

		if o.Vrf != nil {
			qrVrf = *o.Vrf
		}
		qVrf := qrVrf
		if qVrf != "" {

			if err := r.SetQueryParam("vrf", qVrf); err != nil {
				return err
			}
		}
	}

	if o.Vrfn != nil {

		// query param vrf__n
		var qrVrfn string

		if o.Vrfn != nil {
			qrVrfn = *o.Vrfn
		}
		qVrfn := qrVrfn
		if qVrfn != "" {

			if err := r.SetQueryParam("vrf__n", qVrfn); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
